## Container Orchestration

### Docker Compose

## Troubleshooting


FIXME: Enter the containers etc. to see variables etc.


## Summary

With the newfound ability to wrap any Shiny app in a Docker container,
you'll be able to deploy these images to many different hosting
platforms. Of course, there is a lot more to learn, e.g. about handling
dependencies, persisting data across sessions and containers, and so on.
We'll cover these use cases in due time. Until then, celebrate this
milestone, check out further readings, and try to containerize some of
your own Shiny apps.

You can also share Docker images with others. This, however, will require the 
recipient of your app to have Docker installed and be able to run it locally.

In the next Part, we'll cover options for hosting your app, so that others
will only need a browser to be able to access it. No R, Python, or Docker
runtime environment is needed on the user's part. Hosting the app for your
users will also be the preferred option in case you do not want to share
the source code or the Docker image with the users.

Further reading:

-   [Get started with
    Docker](https://docs.docker.com/get-started/)
-   [Docker
    simplified](https://www.freecodecamp.org/news/docker-simplified-96639a35ff36/)
-   [Docker for
    beginners](https://docker-curriculum.com/)
-   [Docker
    glossary](https://docs.docker.com/glossary/)
-   [The Docker
    Handbook](https://docker.farhan.info/)
-   [R Docker
    tutorial](https://jsta.github.io/r-docker-tutorial/)
-   [Docker for R
    users](https://colinfay.me/docker-r-reproducibility/)
-   [An Introduction to
    Rocker](https://journal.r-project.org/archive/2017/RJ-2017-065/RJ-2017-065.pdf)
-   [The
    Rockerverse](https://journal.r-project.org/archive/2020/RJ-2020-007/RJ-2020-007.pdf)
